# statically linking the C runtime on windows seems sensible?
[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-feature=+crt-static"]

# TODO: avoid rust-analyzer crash
[env]
DUCKDB_EXTENSION_MIN_DUCKDB_VERSION = "v1.2.1"
DUCKDB_EXTENSION_NAME = "rusty_quack"
